### ISSUE TITLE
master branch instead of main?

### ISSUE THREAD

**Issue by peter-kehl** [lborb/book#19]
Hi Glyn,

Is there any specific reason for branch/root name `main` rather than `master`?

I've spent at least a couple of minutes in confusion until I've realised it's called `main`. And that is after having previous commits. Imagine how it may confuse newcomers.

**Comment by glyn** [comment]
Hi Peter

Thanks for raising this as it may puzzle others.

In the last year or so, `main` has become a popular default branch name since some people associate `master` with "master/slave" and want to avoid connotations of slavery. I don't personally make that association, but I want to respect people who do.

See https://github.com/github/renaming for more about this.

Regards,
Glyn
